services:
  backend-web:
    build:
      context: .
      dockerfile: container/nginx/Dockerfile
    depends_on:
        - backend-app
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./container/nginx/conf.d:/etc/nginx/conf.d
        - ./container/nginx/ssl:/etc/nginx/ssl

  backend-app:
    build:
      context: .
      dockerfile: container/python/Dockerfile
    expose:
      - 8000
    volumes:
      - ./source/backend:/source
    restart: always
    tty: true
  
  frontend-app:
    build:
      context: .
      dockerfile: container/nodejs/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./source/frontend:/source
      - node_modules:/source/node_modules
    tty: true

volumes:
  node_modules: